# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pixelsforpeace (Frontend)

on:
  push:
    branches:
      - feature/frontend-deployment
  workflow_dispatch:
    inputs:
    logLevel:
      description: "Log level"
      required: true
      default: "warning"

env:
  ## Sets environment variable
  FRONTEND_DIRECTORY: app_frontend
  PUBLISH_PROFILE: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
  APP_NAME: pixelsforpeace
  SLOT_NAME: Production

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.FRONTEND_DIRECTORY }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm prune --production
          npm install
          npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
          package: ./${{ env.FRONTEND_DIRECTORY }}
